package platform

import (
	"encoding/json"
	"fmt"
	"net"
	"net/netip"
	"rillway/internal/config"
	"strings"
)

// PAC bypasses only client-side destinations. A server-side direct route is
// intentionally different: it still passes through the proxy for observation.
func PAC(c config.PAC) (string, error) {
	proxyHost, _, err := net.SplitHostPort(c.ProxyAddress)
	if err != nil {
		return "", err
	}
	proxyHost = strings.TrimSuffix(strings.ToLower(proxyHost), ".")
	selfCIDR := ""
	if ip, err := netip.ParseAddr(proxyHost); err == nil {
		ip = ip.Unmap()
		proxyHost = ip.String()
		selfCIDR = netip.PrefixFrom(ip, ip.BitLen()).String()
	}
	cidrsEnabled := c.EnabledCIDRs()
	for _, p := range cidrsEnabled {
		if _, err := netip.ParsePrefix(p); err != nil {
			return "", err
		}
	}
	domains, _ := json.Marshal(c.EnabledDomains())
	cidrs, _ := json.Marshal(cidrsEnabled)
	proxy, _ := json.Marshal("PROXY " + c.ProxyAddress)
	selfHost, _ := json.Marshal(proxyHost)
	selfRange, _ := json.Marshal(selfCIDR)
	return fmt.Sprintf(`// Generated by Rillway. No automatic DIRECT fallback for public traffic.
var bypassDomains = %s, bypassCIDRs = %s;
var selfHost = %s, selfCIDR = %s;
function addr(s) {
 s=s.replace(/^\[/, "").replace(/\]$/, "").split("%%")[0];
 if(s.indexOf(":")<0){var a=s.split(".");if(a.length!==4)return null;for(var i=0;i<4;i++){if(!/^\d+$/.test(a[i])||+a[i]>255)return null;a[i]=+a[i];}return a;}
 if(s.indexOf(".")>=0){var p=s.lastIndexOf(":"),v=addr(s.slice(p+1));if(!v)return null;s=s.slice(0,p)+":"+((v[0]<<8)|v[1]).toString(16)+":"+((v[2]<<8)|v[3]).toString(16);}
 var h=s.split("::");if(h.length>2)return null;var l=h[0]?h[0].split(":"):[],r=h.length>1&&h[1]?h[1].split(":"):[];
 if(h.length===1&&l.length!==8)return null;var a=l.slice();if(h.length===2){if(l.length+r.length>=8)return null;while(a.length<8-r.length)a.push("0");}a=a.concat(r);var out=[];
 for(var i=0;i<a.length;i++){if(!/^[0-9a-f]{1,4}$/i.test(a[i]))return null;var n=parseInt(a[i],16);out.push(n>>8,n&255);}return out.length===16?out:null;
}
function inside(ip,cidr){var p=cidr.split("/"),a=addr(ip),b=addr(p[0]),bits=+p[1];if(a&&b&&a.length===16&&b.length===4){var mapped=true;for(var k=0;k<10;k++)if(a[k]!==0)mapped=false;if(mapped&&a[10]===255&&a[11]===255)a=a.slice(12);}if(!a||!b||a.length!==b.length)return false;for(var i=0;i<a.length&&bits>0;i++,bits-=8){var mask=bits>=8?255:((255<<(8-bits))&255);if((a[i]&mask)!==(b[i]&mask))return false;}return true;}
function bypassIP(ip){for(var i=0;i<bypassCIDRs.length;i++)if(inside(ip,bypassCIDRs[i]))return true;return false;}
function FindProxyForURL(url,host){
 host=host.toLowerCase().replace(/\.$/, "");
 if(host===selfHost||(selfCIDR&&inside(host,selfCIDR)))return "DIRECT";
 if(isPlainHostName(host)&&host.indexOf(":")<0)return "DIRECT";
 for(var i=0;i<bypassDomains.length;i++){var d=bypassDomains[i].replace(/^\./,"").toLowerCase();if(host===d||host.slice(-(d.length+1))==="."+d)return "DIRECT";}
 if(addr(host)){if(bypassIP(host))return "DIRECT";}
 else {var ips=typeof dnsResolveEx==="function"?dnsResolveEx(host):dnsResolve(host);if(ips){var list=ips.split(";");for(var j=0;j<list.length;j++)if((selfCIDR&&inside(list[j],selfCIDR))||bypassIP(list[j]))return "DIRECT";}}
 return %s;
}
`, domains, cidrs, selfHost, selfRange, proxy), nil
}

func ClientAllowed(remote string, cidrs []string) bool {
	host, _, err := net.SplitHostPort(remote)
	if err != nil {
		return false
	}
	ip, err := netip.ParseAddr(strings.Trim(host, "[]"))
	if err != nil {
		return false
	}
	ip = ip.Unmap()
	for _, s := range cidrs {
		p, err := netip.ParsePrefix(s)
		if err == nil && p.Contains(ip) {
			return true
		}
	}
	return false
}
